import type { Event, TeamMember, Message, SiteSettings, Stats, User } from "./types";

// ── Default Users ──
export const defaultUsers: User[] = [
  {
    id: "u1",
    name: "Super Admin",
    email: "superadmin@bupeic.org",
    role: "super_admin",
    password: "admin123",
  },
  {
    id: "u2",
    name: "Admin User",
    email: "admin@bupeic.org",
    role: "admin",
    password: "admin123",
  },
  {
    id: "u3",
    name: "Editor User",
    email: "editor@bupeic.org",
    role: "editor",
    password: "editor123",
  },
];

// ── Default Events ──
export const defaultEvents: Event[] = [
  {
    id: "e1",
    title: "Startup Pitch Competition 3.0",
    description:
      "Pitch your startup ideas to a panel of judges and investors. Top 3 teams win seed funding and mentorship opportunities.",
    date: "2026-05-15",
    time: "10:00 AM",
    location: "BUP Auditorium",
    status: "upcoming",
    category: "competition",
    attendees: 0,
    maxAttendees: 200,
    registrationLink: "#",
    createdBy: "u1",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "e2",
    title: "Business Case Challenge",
    description:
      "Solve real-world business problems presented by industry partners. Teams of 3-4 compete for the championship title.",
    date: "2026-05-22",
    time: "09:00 AM",
    location: "BUP Conference Hall",
    status: "upcoming",
    category: "competition",
    attendees: 0,
    maxAttendees: 150,
    registrationLink: "#",
    createdBy: "u1",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "e3",
    title: "Innovation Summit 3.0",
    description:
      "A day-long summit featuring keynote speakers, panel discussions, and networking with industry leaders and innovators.",
    date: "2026-06-10",
    time: "09:00 AM",
    location: "BUP Main Campus",
    status: "upcoming",
    category: "seminar",
    attendees: 0,
    maxAttendees: 500,
    registrationLink: "#",
    createdBy: "u2",
    createdAt: "2026-03-10T00:00:00Z",
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "e4",
    title: "Entrepreneurship Workshop Series",
    description:
      "Weekly workshops covering business planning, financial modeling, marketing strategies, and more.",
    date: "2026-04-10",
    time: "03:00 PM",
    location: "BUP Room 301",
    status: "ongoing",
    category: "workshop",
    attendees: 45,
    maxAttendees: 60,
    createdBy: "u2",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "e5",
    title: "Hackathon: Build for Bangladesh",
    description:
      "24-hour hackathon to build technology solutions for local community problems. Open to all university students.",
    date: "2026-03-15",
    time: "08:00 AM",
    location: "BUP CS Lab",
    status: "completed",
    category: "competition",
    attendees: 120,
    maxAttendees: 120,
    createdBy: "u1",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-03-16T00:00:00Z",
  },
  {
    id: "e6",
    title: "BUP Business Fest 2025",
    description:
      "The flagship annual business festival featuring multiple competitive segments, exhibitions, and cultural events.",
    date: "2026-02-20",
    time: "09:00 AM",
    location: "BUP Campus",
    status: "completed",
    category: "fest",
    attendees: 800,
    maxAttendees: 1000,
    createdBy: "u1",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-02-21T00:00:00Z",
  },
];

// ── Default Team Members ──
export const defaultTeamMembers: TeamMember[] = [
  {
    id: "t1",
    name: "Md. Samiul Hossain",
    position: "President",
    department: "Executive Panel",
    email: "president@bupeic.org",
    bio: "Leading BUP EIC with a vision to empower student entrepreneurs.",
    social: { facebook: "#", linkedin: "#" },
    order: 1,
    category: "executive",
    status: "active",
  },
  {
    id: "t2",
    name: "Ibrahim Hossain Niloy",
    position: "Vice President",
    department: "Executive Panel",
    email: "vp@bupeic.org",
    bio: "Driving innovation and collaboration across all departments.",
    social: { facebook: "#", linkedin: "#" },
    order: 2,
    category: "executive",
    status: "active",
  },
  {
    id: "t3",
    name: "Fariha Tasnim",
    position: "General Secretary",
    department: "Executive Panel",
    email: "gs@bupeic.org",
    bio: "Ensuring smooth operations and effective communication.",
    social: { facebook: "#", linkedin: "#" },
    order: 3,
    category: "executive",
    status: "active",
  },
  {
    id: "t4",
    name: "Nusrat Jahan",
    position: "Treasurer",
    department: "Executive Panel",
    email: "treasurer@bupeic.org",
    bio: "Managing finances with transparency and accountability.",
    social: { facebook: "#", linkedin: "#" },
    order: 4,
    category: "executive",
    status: "active",
  },
  {
    id: "t5",
    name: "Tanvir Ahmed",
    position: "Director",
    department: "Marketing & Communications",
    email: "marketing@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 5,
    category: "committee",
    status: "active",
  },
  {
    id: "t6",
    name: "Raisa Kabir",
    position: "Director",
    department: "Events & Logistics",
    email: "events@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 6,
    category: "committee",
    status: "active",
  },
  {
    id: "t7",
    name: "Shahriar Rahman",
    position: "Director",
    department: "Finance & Sponsorship",
    email: "finance@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 7,
    category: "committee",
    status: "active",
  },
  {
    id: "t8",
    name: "Ayesha Siddika",
    position: "Director",
    department: "Human Resources",
    email: "hr@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 8,
    category: "committee",
    status: "active",
  },
  {
    id: "t9",
    name: "Mehedi Hasan",
    position: "Director",
    department: "Technology & Innovation",
    email: "tech@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 9,
    category: "committee",
    status: "active",
  },
  {
    id: "t10",
    name: "Sabrina Akter",
    position: "Director",
    department: "Creative & Design",
    email: "creative@bupeic.org",
    social: { facebook: "#", linkedin: "#" },
    order: 10,
    category: "committee",
    status: "active",
  },
];

// ── Default Messages ──
export const defaultMessages: Message[] = [
  {
    id: "m1",
    name: "Rafiul Islam",
    email: "rafiul@example.com",
    subject: "Interested in joining BUP EIC",
    message:
      "Hi, I'm a 2nd year student at BUP and I'm very interested in joining the club. Could you please let me know about the recruitment process?",
    status: "unread",
    createdAt: "2026-04-01T14:30:00Z",
  },
  {
    id: "m2",
    name: "Tasneem Ara",
    email: "tasneem@example.com",
    subject: "Partnership Proposal",
    message:
      "We would like to propose a partnership between our organization and BUP EIC for an upcoming business event. Please let me know the best time to discuss.",
    status: "unread",
    createdAt: "2026-03-31T09:15:00Z",
  },
  {
    id: "m3",
    name: "Kamal Uddin",
    email: "kamal@example.com",
    subject: "Speaker opportunity for Innovation Summit",
    message:
      "I'd love to be a speaker at your upcoming Innovation Summit. I have experience in startup ecosystem development and can share valuable insights.",
    status: "read",
    createdAt: "2026-03-29T16:45:00Z",
  },
  {
    id: "m4",
    name: "Nadia Rahman",
    email: "nadia@example.com",
    subject: "Feedback on Business Fest 2025",
    message:
      "I attended the Business Fest and wanted to share my positive experience. The event was very well organized! Would love to see more networking sessions next time.",
    status: "replied",
    createdAt: "2026-03-25T11:00:00Z",
    repliedAt: "2026-03-26T09:00:00Z",
    repliedBy: "u2",
  },
  {
    id: "m5",
    name: "Jubayer Hossain",
    email: "jubayer@example.com",
    subject: "Sponsorship inquiry",
    message:
      "Our company is interested in sponsoring BUP EIC events. Could you share a sponsorship package or proposal?",
    status: "read",
    createdAt: "2026-03-20T13:30:00Z",
  },
];

// ── Default Settings ──
export const defaultSettings: SiteSettings = {
  siteName: "BUP Entrepreneurship & Innovation Club",
  description:
    "BUP EIC empowers students to turn ideas into impact through creativity and teamwork. Driven by our motto, Innovate, Collaborate, and Elevate.",
  email: "bupeic.official@gmail.com",
  phone: "01875-814089",
  address: "Bangladesh University of Professionals, Mirpur Cantonment, Dhaka 1216",
  social: {
    facebook: "https://www.facebook.com/profile.php?id=61583074589275",
    instagram: "",
    linkedin: "",
    youtube: "",
    twitter: "",
  },
  announcement: "",
  heroTitle: "Innovate. Collaborate. Elevate.",
  heroDescription: "Join the community that transforms bold ideas into real-world impact through creativity, teamwork, and innovation.",
};

// ── Default Stats ──
export const defaultStats: Stats = {
  followers: 950,
  events: 50,
  members: 500,
  partners: 20,
  alumni: 500,
};
